<?php

/**
 * @file
 * Commerce coffee
 * Hooks into Coffee module to provide Commerce commands.
 */

/**
 * Implements hook_permission().
 */
function commerce_coffee_permission() {
  $permissions = array(
    'use commerce coffee' => array(
      'title' => t('Access Commerce Coffee'),
      'description' => t('Permit Commerce-related commands within the Coffee interface.'),
    ),
  );

  return $permissions;
}

/**
 * Implements hook_coffee_command().
 *
 * Feeds Commerce-related commands into Coffee if proper permissions are set.
 */
function commerce_coffee_coffee_command($op) {
  if (user_access('use commerce coffee')) {
    module_load_include('inc', 'commerce_coffee', 'commerce_coffee.includes');
    return commerce_coffee_get_commands(check_plain($op));
  }
}
