; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.43"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[commerce_kickstart][download][type] = ""
projects[commerce_kickstart][download][url] = ""
projects[commerce_kickstart][type] = "module"
projects[commerce_kickstart][version] = "2.36"

projects[views_bulk_operations][version] = "3.3"

projects[addressfield][version] = "1.2"

projects[admin_views][version] = "1.5"

projects[advanced_help][version] = "1.3"

projects[auto_entitylabel][subdir] = "contrib"
projects[auto_entitylabel][version] = "1.3"

projects[autocomplete_deluxe][subdir] = "contrib"
projects[autocomplete_deluxe][version] = "2.1"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "3.1"

projects[service_links][version] = "2.3+0-dev"

projects[block_class][subdir] = "contrib"
projects[block_class][version] = "2.3"

projects[breakpoints][subdir] = "contrib"
projects[breakpoints][version] = "1.4"

projects[ctools][version] = "1.9"

projects[cer][subdir] = "contrib"
projects[cer][version] = "3.0-alpha7"

projects[charts][subdir] = "contrib"
projects[charts][version] = "2.0-rc1"

projects[chosen][version] = "2.0-beta4+1-dev"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.17"

projects[cloud_zoom][version] = "1.1+1-dev"

projects[coffee][subdir] = "contrib"
projects[coffee][version] = "2.2"

projects[colorbox][version] = "2.10"
projects[colorbox][patches][] = "https://www.drupal.org/files/issues/plugin_version_detection-2360375-9.patch"

projects[colorbox_node][subdir] = "contrib"
projects[colorbox_node][version] = "3.5"

projects[commerce][version] = "1.13"

projects[commerce_add_to_cart_confirmation][version] = "1.0-rc2"

projects[commerce_addressbook][version] = "2.0-rc9"

projects[commerce_amex][version] = "1.1"

projects[commerce_autosku][version] = "1.1+12-dev"

projects[commerce_backoffice][version] = "1.5"

projects[commerce_checkout_progress][version] = "1.4"

projects[commerce_discount][version] = "1.0-alpha7"

projects[commerce_extra_price_formatters][version] = "1.1+7-dev"

projects[commerce_fancy_attributes][version] = "1.0"

projects[commerce_features][version] = "1.1"

projects[commerce_feeds][subdir] = "contrib"
projects[commerce_feeds][version] = "1.4"

projects[commerce_flat_rate][version] = "1.0-beta2"

projects[commerce_hosted_pci][version] = "1.0-rc2"

projects[commerce_message][version] = "1.0-rc4"

projects[commerce_migrate][version] = "1.2"
projects[commerce_migrate][patches][] = "https://www.drupal.org/files/issues/reference_fields_should-2701333-3.patch"

projects[commerce_paypal][version] = "2.3"
projects[commerce_paypal][patches][] = "https://www.drupal.org/files/issues/commerce_paypal-addressfield-default-values-2458721-1.patch"

projects[commerce_payleap][version] = "1.1"

projects[commerce_reports][subdir] = "contrib"
projects[commerce_reports][version] = "4.0-beta3"

projects[commerce_search_api][version] = "1.4"

projects[commerce_shipping][version] = "2.2"

projects[connector][version] = "1.0-beta2"

projects[countries][version] = "2.3"

projects[crumbs][version] = "1.10"

projects[facetapi][version] = "1.5"
projects[facetapi][patches][] = "https://www.drupal.org/files/issues/notice_undefined-2378693-3.patch"

projects[date][version] = "2.9"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[distro_update][version] = "1.0-beta4"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.14"

projects[ds_extra_layouts][subdir] = "contrib"
projects[ds_extra_layouts][version] = "1.1"

projects[editablefields][subdir] = "contrib"
projects[editablefields][version] = "1.0-alpha2+14-dev"

projects[elements][subdir] = "contrib"
projects[elements][version] = "1.4"

projects[entity][version] = "1.7"

projects[entity_embed][subdir] = "contrib"
projects[entity_embed][version] = "1.0-alpha4"

projects[entityreference][version] = "1.1"
projects[entityreference][patches][] = "http://drupal.org/files/1580348-universal-formatters-17.patch"

projects[environment_indicator][subdir] = "contrib"
projects[environment_indicator][version] = "2.8"

projects[escape_admin][subdir] = "contrib"
projects[escape_admin][version] = "1.2"

projects[eva][version] = "1.2"

projects[features_extra][subdir] = "contrib"
projects[features_extra][version] = "1.0"

projects[features][version] = "2.10"
projects[features][patches][] = "https://www.drupal.org/files/issues/ignore_hidden_modules-2479803-1.patch"

projects[features_override][version] = "2.0-rc3"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-beta2"

projects[feeds_tamper][subdir] = "contrib"
projects[feeds_tamper][version] = "1.1"

projects[fences][version] = "1.2"

projects[ffc][subdir] = "contrib"
projects[ffc][version] = "1.0-beta2"

projects[field_extractor][version] = "1.3"

projects[field_formatter_settings][subdir] = "contrib"
projects[field_formatter_settings][version] = "1.1"

projects[field_multiple_limit][subdir] = "contrib"
projects[field_multiple_limit][version] = "1.0-alpha4+2-dev"

projects[field_validation][subdir] = "contrib"
projects[field_validation][version] = "2.6"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-beta2"

projects[file_entity_inline][subdir] = "contrib"
projects[file_entity_inline][version] = "1.0-beta1"

projects[filefield_paths][subdir] = "contrib"
projects[filefield_paths][version] = "1.0"

projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.10"

projects[picture][subdir] = "contrib"
projects[picture][version] = "2.13"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[hierarchical_select][subdir] = "contrib"
projects[hierarchical_select][version] = "3.0-beta4"

projects[http_client][version] = "2.4"

projects[icon_tabs][subdir] = "contrib"
projects[icon_tabs][version] = "1.5"

projects[image_delta_formatter][version] = "1.0-rc1"

projects[imagecache_actions][subdir] = "contrib"
projects[imagecache_actions][version] = "1.7"

projects[imageapi_optimize][subdir] = "contrib"
projects[imageapi_optimize][version] = "1.2"

projects[imagezoom][subdir] = "contrib"
projects[imagezoom][version] = "2.0-beta2"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.10"

projects[imce_tools][subdir] = "contrib"
projects[imce_tools][version] = "1.2"

projects[imce_plupload][subdir] = "contrib"
projects[imce_plupload][version] = "2.0"

projects[inline_conditions][version] = "1.0-alpha7"

projects[inline_entity_form][version] = "1.6"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.7"

projects[libraries][version] = "2.2"

projects[link][version] = "1.4"

projects[linkit][subdir] = "contrib"
projects[linkit][version] = "3.5"

projects[mailcontrol][subdir] = "contrib"
projects[mailcontrol][version] = "1.0"

projects[mailsystem][version] = "2.34"
projects[mailsystem][patches][] = "https://www.drupal.org/files/mailsystem.1534706.6.patch"

projects[menu_attributes][version] = "1.0"

projects[message][version] = "1.11"
projects[message][patches][] = "https://www.drupal.org/files/issues/message-mysql57_compatibility-2629474-4.patch"

projects[message_notify][version] = "2.5"

projects[migrate][version] = "2.8"

projects[migrate_d2d][subdir] = "contrib"
projects[migrate_d2d][version] = "2.1"

projects[migrate_extras][version] = "2.5"
projects[migrate_extras][patches][] = "http://drupal.org/files/migrate_extras-fix-destid2-array-1951904-4.patch"

projects[mimemail][version] = "1.0-beta4"

projects[module_filter][version] = "2.0"

projects[oauthconnector][version] = "1.0-beta2"

projects[oauth][version] = "3.2"
projects[oauth][patches][] = "http://drupal.org/files/980340-d7.patch"

projects[pathauto][version] = "1.3"

projects[plupload][subdir] = "contrib"
projects[plupload][version] = "1.7"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc3"

projects[rules][version] = "2.9"

projects[search_api][version] = "1.18"

projects[search_api_db][version] = "1.5"

projects[search_api_ranges][version] = "1.5"
projects[search_api_ranges][patches][] = "https://drupal.org/files/issues/search_api_ranges-rewrite-data-alteration-callback-2001846-4.patch"

projects[search_api_sorts][version] = "1.6"

projects[searchapimultiaggregate][subdir] = "contrib"
projects[searchapimultiaggregate][version] = "1.2"

projects[special_menu_items][version] = "2.0"

projects[stringoverrides][subdir] = "contrib"
projects[stringoverrides][version] = "1.8"

projects[strongarm][version] = "2.0"

projects[table_element][subdir] = "contrib"
projects[table_element][version] = "1.0-beta5"

projects[taxonomy_menu][version] = "1.5"

projects[title][version] = "1.0-alpha8"

projects[token][version] = "1.6"
projects[token][patches][] = "http://drupal.org/files/token-token_asort_tokens-1712336_0.patch"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_color_variations][download][type] = ""
projects[trf_color_variations][download][url] = ""
projects[trf_color_variations][type] = "module"
projects[trf_color_variations][subdir] = "features"
projects[trf_color_variations][version] = "0.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_ief][download][type] = ""
projects[trf_ief][download][url] = ""
projects[trf_ief][type] = "module"
projects[trf_ief][subdir] = "custom"
projects[trf_ief][version] = "1.3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_image_variations][download][type] = ""
projects[trf_image_variations][download][url] = ""
projects[trf_image_variations][type] = "module"
projects[trf_image_variations][subdir] = "features"
projects[trf_image_variations][version] = "0.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_price_variations][download][type] = ""
projects[trf_price_variations][download][url] = ""
projects[trf_price_variations][type] = "module"
projects[trf_price_variations][subdir] = "features"
projects[trf_price_variations][version] = "0.11"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_ring_taxonomies][download][type] = ""
projects[trf_ring_taxonomies][download][url] = ""
projects[trf_ring_taxonomies][type] = "module"
projects[trf_ring_taxonomies][subdir] = "features"
projects[trf_ring_taxonomies][version] = "0.15"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_ring_type][download][type] = ""
projects[trf_ring_type][download][url] = ""
projects[trf_ring_type][type] = "module"
projects[trf_ring_type][subdir] = "features"
projects[trf_ring_type][version] = "0.49"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_ring_variations][download][type] = ""
projects[trf_ring_variations][download][url] = ""
projects[trf_ring_variations][type] = "module"
projects[trf_ring_variations][subdir] = "features"
projects[trf_ring_variations][version] = "0.30"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_site_images][download][type] = ""
projects[trf_site_images][download][url] = ""
projects[trf_site_images][type] = "module"
projects[trf_site_images][subdir] = "features"
projects[trf_site_images][version] = "0.16"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_site_paths][download][type] = ""
projects[trf_site_paths][download][url] = ""
projects[trf_site_paths][type] = "module"
projects[trf_site_paths][subdir] = "features"
projects[trf_site_paths][version] = "0.10"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_site_settings][download][type] = ""
projects[trf_site_settings][download][url] = ""
projects[trf_site_settings][type] = "module"
projects[trf_site_settings][subdir] = "features"
projects[trf_site_settings][version] = "0.9"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_site_text][download][type] = ""
projects[trf_site_text][download][url] = ""
projects[trf_site_text][type] = "module"
projects[trf_site_text][subdir] = "features"
projects[trf_site_text][version] = "0.11"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_store_shipping][download][type] = ""
projects[trf_store_shipping][download][url] = ""
projects[trf_store_shipping][type] = "module"
projects[trf_store_shipping][subdir] = "features"
projects[trf_store_shipping][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_store_taxes][download][type] = ""
projects[trf_store_taxes][download][url] = ""
projects[trf_store_taxes][type] = "module"
projects[trf_store_taxes][subdir] = "features"
projects[trf_store_taxes][version] = "0.3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_title_variations][download][type] = ""
projects[trf_title_variations][download][url] = ""
projects[trf_title_variations][type] = "module"
projects[trf_title_variations][subdir] = "features"
projects[trf_title_variations][version] = "0.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_user_settings][download][type] = ""
projects[trf_user_settings][download][url] = ""
projects[trf_user_settings][type] = "module"
projects[trf_user_settings][subdir] = "features"
projects[trf_user_settings][version] = "0.3"

projects[typogrify][subdir] = "contrib"
projects[typogrify][version] = "1.0-rc10"

projects[views][version] = "3.13"

projects[views_data_export][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta9"

projects[views_date_format_sql][subdir] = "contrib"
projects[views_date_format_sql][version] = "3.3"

projects[views_megarow][version] = "1.5"

; Themes
projects[omega][version] = "3.1"

projects[omega_kickstart][version] = "3.4"

projects[shiny][version] = "1.7"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_ring_similar][download][type] = ""
projects[trf_ring_similar][download][url] = ""
projects[trf_ring_similar][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_site_home][download][type] = ""
projects[trf_site_home][download][url] = ""
projects[trf_site_home][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_site_search][download][type] = ""
projects[trf_site_search][download][url] = ""
projects[trf_site_search][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf][download][type] = ""
projects[trf][download][url] = ""
projects[trf][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trf_admin][download][type] = ""
projects[trf_admin][download][url] = ""
projects[trf_admin][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[paymill][download][type] = ""
libraries[paymill][download][url] = ""
libraries[paymill][directory_name] = "paymill"
libraries[paymill][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery_ui_spinner][download][type] = ""
libraries[jquery_ui_spinner][download][url] = ""
libraries[jquery_ui_spinner][directory_name] = "jquery_ui_spinner"
libraries[jquery_ui_spinner][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[chosen][download][type] = ""
libraries[chosen][download][url] = ""
libraries[chosen][directory_name] = "chosen"
libraries[chosen][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.bxslider][download][type] = ""
libraries[jquery.bxslider][download][url] = ""
libraries[jquery.bxslider][directory_name] = "jquery.bxslider"
libraries[jquery.bxslider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[yotpo-php][download][type] = ""
libraries[yotpo-php][download][url] = ""
libraries[yotpo-php][directory_name] = "yotpo-php"
libraries[yotpo-php][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[selectnav.js][download][type] = ""
libraries[selectnav.js][download][url] = ""
libraries[selectnav.js][directory_name] = "selectnav.js"
libraries[selectnav.js][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ie7-js][download][type] = ""
libraries[ie7-js][download][url] = ""
libraries[ie7-js][directory_name] = "ie7-js"
libraries[ie7-js][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[cloud-zoom][download][type] = ""
libraries[cloud-zoom][download][url] = ""
libraries[cloud-zoom][directory_name] = "cloud-zoom"
libraries[cloud-zoom][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery_expander][download][type] = ""
libraries[jquery_expander][download][url] = ""
libraries[jquery_expander][directory_name] = "jquery_expander"
libraries[jquery_expander][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[elevatezoom][download][type] = ""
libraries[elevatezoom][download][url] = ""
libraries[elevatezoom][directory_name] = "elevatezoom"
libraries[elevatezoom][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[plupload][download][type] = ""
libraries[plupload][download][url] = ""
libraries[plupload][directory_name] = "plupload"
libraries[plupload][type] = "library"

