options:
  formatter: stylish
  cache-config: true
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 2
  single-line-per-selector: 1

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 0
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 0
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format: 0
  function-name-format: 1
  id-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 0
  variable-name-format: 0

  # Style Guide
  attribute-quotes: 2
  bem-depth: 0
  border-zero:
  - 1
  - convention: 'none'
  brace-style: 1
  clean-import-paths: 0
  empty-args: 2
  hex-length: 1
  hex-notation: 1
  indentation: 1
  leading-zero:
  - 1
  - include: true
  nesting-depth:
  - 1
  - max-depth: 3
  property-sort-order: 0
  pseudo-element: 2
  quotes: 1
  shorthand-values: 0
  url-quotes: 2
  variable-for-property: 0
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 1
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 1
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 1
