<?php
/**
* Implements hook_inline_entity_form_table_fields_alter().
*/
function ringsforever_ief_inline_entity_form_table_fields_alter(&$fields, $context) {
    $is_my_content_type = FALSE;
    foreach ($context['allowed_bundles'] as $bundle) {
      if ($bundle=='rings') {
        $is_my_content_type = TRUE;
      }
    }
    if ($is_my_content_type) {
      // Remove 'Status' field
      unset($fields['status']);
      // Add 'Description' field
      $fields['field_description'] = array(
        'type' => 'field',
        'label' => t('Description'),
        'weight' => 101,
      );
    }
}
