<?php
/**
 * Modifies the default inline entity form table on node edit forms.
 *
 * @link https://drupal.org/node/2091585#comment-7876517
 *
 * 
 * @see profiles/commerce_kickstart/modules/contrib/inline_entity_form/inline_entity_form.api.php line 59
 * 
 * Implements hook_inline_entity_form_table_fields_alter().
 */

function ringsforever_ief_inline_entity_form_table_fields_alter(&$fields, $context) {

  // "Related Rings" field
  $is_my_content_type = FALSE;
  foreach ($context['allowed_bundles'] as $bundle) {
    if ($bundle=='rings') {
      $is_my_content_type = TRUE;
    }
  }
  if ($is_my_content_type) {

    // Remove 'Status' field
    unset($fields['status']);

    // Add 'Description' field
    $fields['field_description'] = array(
      'type' => 'field',
      'label' => t('Description'),
      'weight' => 101,
    );
  }

  // Product variations
  if ($context['parent_entity_type'] == 'node' && $context['entity_type'] == 'commerce_product') {
    // Remove 'Variation title' field
    unset($fields['commerce_product-title']);

    // Remove 'Description' field
    unset($fields['field_description']);
  }
}
