<?php

/**
 * Implements hook_commerce_shipping_service_rate_options_alter()
 */
function trf_shipping_sort_commerce_shipping_service_rate_options_alter(&$options, $order) {
    // If there is more than one shipping service available, sort them by line item unit price
    if (count($order->shipping_rates) > 1) {
        // Collect rates from line items
        $service_prices = array();
        foreach ($order->shipping_rates as $service => $line_item) {
            $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
            $unit_price = $line_item_wrapper->commerce_unit_price->value();
          $service_prices[$service] = $unit_price['amount'];
        }

        // array_multisort can be used here because $options and $order->shipping_rates contain the same number of elements (i.e. services).
        array_multisort($service_prices, SORT_NUMERIC, SORT_ASC, $options);
    }
}
