<?php
/**
 * @file
 * Code for the TRF site path settings feature.
 */

include_once 'trf_ring_taxonomies.features.inc';

/**
 * Implements hook_preprocess_views_view().
 *
 * Overrides commerce_kickstart_taxonomy to set "title to display" as the
 * collection title in the view header.
 *
 * Also removes collection_title_url variable as we've removed the image that
 * would be used as the background.
 */
function trf_ring_taxonomies_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  if ($view->name == 'collection_products') {
    if ($view->current_display == 'page') {
      // Keep the previous theming.
      $vars['classes_array'][] = 'view-collection-taxonomy-term';
      $tid = $view->args['0'];
      $term = taxonomy_term_load($tid);
      $vars['collection_title'] = $term->field_cat_title['und'][0]['safe_value'];
    }
  }
}
